config/routes.rb
Calcacademy::Application.routes.draw do
  root 'home#index'

  devise_for :users, :controllers => {:omniauth_callbacks => "users/omniauth_callbacks"}

  scope :my_scope do
    resources :users
  end
  # post '/users/omniauth_authorize' => 'users#omniauth_authorize'
  post '/add_score' => 'users#add_score'
  post '/add_topic' => 'users#add_topic'
  post '/add_subtopic' => 'users#add_subtopic'
  resources :subjects do
    member do
      post 'index'
    end
  end
  resources :topics
  resources :subtopics
  resources :questions
  resources :answers
  # get 'sessions/new' => 'sessions#new'
  # post 'sessions' => 'sessions#create'
  # delete 'logout' => 'sessions#destroy'
  # Example of regular route:
  #   get 'products/:id' => 'catalog#view'

  # Example of named route that can be invoked with purchase_url(id: product.id)
  #   get 'products/:id/purchase' => 'catalog#purchase', as: :purchase

  # Example resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Example resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Example resource route with sub-resources:
    # resources :subjects do
    #   resources :topics
    # end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end
  
  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end
end

app/models/subject.rb
class Subject < ActiveRecord::Base

  has_many :topics, :dependent => :destroy
  has_and_belongs_to_many :users

  validates :name, presence: true

end

app/controllers/subjects_controller.rb
class SubjectsController < ApplicationController
  # before_action :ensure_admin, only: [:edit, :update, :destroy, :new, :create]
  # before_action :current_user #, only: [:edit, :update, :destroy, :new, :create]
  
  before_action :authenticate_user!
  
  def index
    @subjects = Subject.all
    p @subjects
  end

  def edit
    @subject = Subject.find(params[:id])
  end

  def update
    @subject = Subject.find(params[:id])
    if @subject.update_attributes(subject_params)
      redirect_to subjects_path
    else
      render :edit
    end
  end
  
  def new
    @subject = Subject.new
  end
  def create
    @subject = Subject.new(subject_params)
    if @subject.save
      redirect_to subjects_path
    else
      render :new
    end
  end
  def destroy
    subject = Subject.find(params[:id])
    subject.destroy
    redirect_to :back
  end

  private
  
  def subject_params
    params.require(:new_subject).permit(:name)
  end

end

app/views/subjects/edit.html.haml
%h1 Edit Subject

= render partial: '/subjects/partials/form'

app/views/subjects/index.html.haml
- if current_user
  %h1 Subjects

  - @subjects.each do |subject| 
    = link_to topics_path+"?subject_id=#{subject.id}" do
      .subject{class: "#{'finished' if current_user.finished_with?(subject)}"}
        = subject.name
    - if current_user && current_user.admin?    
      .admin
        = link_to('edit', edit_subject_path(subject), class:'edit')
        = link_to('delete', subject_path(subject), class:'delete', method: :delete, confirm: 'Are you sure you want to delete this subject?')
    %br
    %br
    %br
    %br
- else
  Please 
  %a{:href=>"/users/new"}
    Sign-up
  or 
  %a{:href=>"/sessions/new"}
    Login 
  to start learning!

app/views/subjects/new.html.haml
%h1 New Subject

= render partial: '/subjects/partials/form'